site_name: stat gen playground

theme:
    name: readthedocs
    # Use Highlight.js library for syntax highlighting for code blocks
    highlightjs: true

nav:
    - Home: index.md
    - Bash: 
        - Tips and examples: bash/tips_examples.md
        - conda: bash/conda.md
        - ssh: bash/ssh.md
        - vim: bash/vim.md
    - Bioinformatics:
        - bcftools: bioinformatics/bcftools.md
        - plink: bioinformatics/plink.md
    - Miscellaneous:
        - Setting up mkdocs: misc/setting_up_mkdocs.md
    - Python:
        - Tips and examples: python/tips_examples.md
        - matplotlib examples: python/matplotlib_examples.md
        - pandas examples: python/pandas_examples.md

markdown_extensions:
    - attr_list
    # Enable highlighted note/important blocks
    - admonition    
