site_name: stat gen playground

theme:
    name: readthedocs
    # Use Highlight.js library for syntax highlighting for code blocks
    highlightjs: true

nav:
    - Home: index.md
    # - "Bash": 
    - Miscellaneous:
        - "Setting up mkdocs": misc/setting_up_mkdocs.md

markdown_extensions:
    - attr_list
