site_name: stat gen playground

theme:
    name: readthedocs

nav:
    - Home: index.md
    # - "Bash": 
    - Miscellaneous:
        - "Setting up mkdocs": misc/setting_up_mkdocs.md

markdown_extensions:
    - attr_list
